/*using Databasechanging;
using System.Xml;

public class Program
{
    public struct xmlSettings
    {
        public string userName;
        public string serverName;
        public string dbName;
        public string dbPort;
        public string multidb;
        public bool success;
        public string errorMessage;

    }
    public static void Main()
    {
        XmlWriterSettings settings = new XmlWriterSettings();
        settings.Indent = true;
        clsXMLData settings2 = new clsXMLData();


        XmlWriter writer = XmlWriter.Create("Settings.xml", settings);
        writer.WriteStartDocument();
        writer.WriteComment("This file is generated by the program.");
        writer.WriteStartElement("Settings");
        writer.WriteAttributeString("USER", "settings2.userName");
        writer.WriteAttributeString("SERVER", "settings2.serverName");
        writer.WriteElementString("DATABASE", "setting2.dbName");
        writer.WriteElementString("PORT", "setting2.dbPort");
        writer.WriteStartElement("MULTIDATABASE");
        //writer.WriteElementString("BrandName", "X Soap");
        //writer.WriteElementString("Manufacturer", "X Company");
        writer.WriteEndElement();
        writer.WriteEndDocument();

        writer.Flush();
        writer.Close();
    }
}*/