DELIMITER ***
DROP PROCEDURE IF EXISTS NEW;
CREATE PROCEDURE NEW()
BEGIN
DECLARE V_DONE INT DEFAULT FALSE;
DECLARE C DECIMAL(10,0);
DECLARE V_COCODE CHAR(15);
DECLARE V_BRCODE CHAR(15);
DECLARE V_FYCODE CHAR(15);
DECLARE V_FNCODE CHAR(15);
DECLARE V_DOCNO CHAR(15);
DECLARE cur CURSOR FOR SELECT COCODE,BRCODE,FYCODE,FNCODE,DOCNO FROM HDATA;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_DONE = TRUE;
OPEN cur;
testLoop: LOOP
    FETCH cur INTO V_COCODE,V_BRCODE,V_FYCODE,V_FNCODE,V_DOCNO;
    CALL SP_ACCOUNTPOSTING(V_COCODE,V_BRCODE,V_FYCODE,V_FNCODE,V_DOCNO);
    IF V_DONE THEN
      LEAVE testLoop;
    END IF;
  END LOOP testLoop;
CLOSE cur;
END
***